version: .{build}
clone_folder: c:\work\autofac.quartz

pull_requests:
  do_not_increment_build_number: true
  
nuget:
  disable_publish_on_pr: true
  
os: Visual Studio 2015

cache:
  - ResharperCaches -> Solutions\**\packages.config
  
install:
  - cmd: git submodule update --init --recursive
  - ps: >-
      dotnet --version ;
      choco install GitVersion.Portable -y ;
      choco install Nuget.CommandLine -y ;
      choco install resharper-clt.portable -y ;
      choco install nunit.portable -y ;
      choco install opencover.portable -y ; 
      choco install reportgenerator.portable -y ;
      choco install msbuild-xslt -pre -y;

environment:
  coveralls_repo_token:
    secure: yDtlwZxOr+meDM0iMA3pWo3VO+t2oRDIjf+accbVz3N2NO74W6yhF7lgRjw9B2Ek
  appveyor_cache_entry_zip_args: -t7z -m0=lzma -mx=5 -ms=on
    
before_build:
  - cmd: nuget restore Solutions/Autofac.Extras.Quartz.sln
  - ps: gitversion /output buildserver /updateAssemblyInfo .\Common\AssemblyVersion.cs /ensureAssemblyInfo

build_script:
  - cmd: '"%ProgramFiles(x86)%\MSBuild\14.0\Bin\MSBuild.exe" Build\Build.proj /t:Build;RunTests;UploadNUnitCoverage;FindDuplicates;InspectCode;PackageNuget /p:IsDesktopBuild=false'

test: off
  
artifacts:
  - path: Drops/**/*.nupkg
    name: Nugets
  - path: Drops/Duplicates/CodeDuplicatesReport.html
    name: CodeDuplicates
  - path: Drops/Inspections/CodeInspectionsReport.html
    name: CodeInspections

deploy:
  - provider: NuGet
    api_key:
      secure: yDtlwZxOr+meDM0iMA3pWo3VO+t2oRDIjf+accbVz3N2NO74W6yhF7lgRjw9B2Ek
    on:
      branch: 
        - develop
        - /release\/v.*/
        - /releases.*/
        - /hotfixes.*/
